---
- hosts: webservers
  become: yes
  vars_files:
    - secrets.yml
  tasks:
    - name: INSTALL APACHE2
      apt: name=apache2 update_cache=yes state=latest
    
    - name: ENABLED MOD_REWRITE
      apache2_module: name=rewrite state=present
      notify:
        - RESTART APACHE2
    - name: Deploy HTML Page
      copy:
        src: /var/lib/jenkins/workspace/Sports-page-test/templates/index.html
        dest: /var/www/html

    - name: Deploy CSS Files
      copy:
        src: /var/lib/jenkins/workspace/Sports-page-test/static/styles.css
        dest: /var/www/html/css

  handlers:
    - name: RESTART APACHE2
      service: name=apache2 state=restarted
