FROM python
COPY ./static /webapp/static/
COPY ./templates/ webapp/templates/
COPY app.py /webapp/
EXPOSE 5000
CMD python /webapp/app.py
FROM python
COPY ./static /webapp/static/
COPY ./templates/ webapp/templates/
COPY app.py /webapp/
EXPOSE 5000
CMD python /webapp/app.py
FROM python
COPY ./static /webapp/static/
COPY ./templates/ webapp/templates/
COPY app.py /webapp/
EXPOSE 5000
CMD python /webapp/app.py
FROM python
COPY ./static /webapp/static/
COPY ./templates/ webapp/templates/
COPY app.py /webapp/
EXPOSE 5000
CMD python /webapp/app.py
FROM python
COPY ./static /webapp/static/
COPY ./templates/ webapp/templates/
COPY app.py /webapp/
EXPOSE 5000
CMD python /webapp/app.py
FROM python
COPY ./static /webapp/static/
COPY ./templates/ webapp/templates/
COPY app.py /webapp/
EXPOSE 5000
CMD python /webapp/app.py
FROM python
COPY ./static /webapp/static/
COPY ./templates/ webapp/templates/
COPY app.py /webapp/
EXPOSE 5000
CMD python /webapp/app.py
FROM python
COPY ./static /webapp/static/
COPY ./templates/ webapp/templates/
COPY app.py /webapp/
EXPOSE 5000
CMD python /webapp/app.py
FROM python
COPY ./static /webapp/static/
COPY ./templates/ webapp/templates/
COPY app.py /webapp/
EXPOSE 5000
CMD python /webapp/app.py
FROM python
COPY ./static /webapp/static/
COPY ./templates/ webapp/templates/
COPY app.py /webapp/
EXPOSE 5000
CMD python /webapp/app.py
FROM python
COPY ./static /webapp/static/
COPY ./templates/ webapp/templates/
COPY app.py /webapp/
EXPOSE 5000
CMD python /webapp/app.py
FROM python
RUN pip install flask
COPY ./static /webapp/static/
COPY ./templates/ webapp/templates/
COPY app.py /webapp/
EXPOSE 5000
CMD python /webapp/app.py
FROM python
RUN pip install flask
COPY ./static /webapp/static/
COPY ./templates/ webapp/templates/
COPY app.py /webapp/
EXPOSE 5000
CMD python /webapp/app.py
FROM python
RUN pip install flask
COPY ./static /webapp/static/
COPY ./templates/ webapp/templates/
COPY app.py /webapp/
EXPOSE 5000
CMD python /webapp/app.py
FROM python
RUN pip install flask
COPY ./static /webapp/static/
COPY ./templates /webapp/templates/
COPY app.py /webapp/
EXPOSE 5000
CMD python /webapp/app.py
